# Generated by Django 4.2.7 on 2023-11-08 00:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IoTDevices',
            fields=[
                ('brand', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('product_type', models.CharField(max_length=32)),
                ('release_date', models.IntegerField(blank=True)),
                ('price', models.IntegerField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkDevices',
            fields=[
                ('brand', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('product_type', models.CharField(max_length=32)),
                ('release_date', models.IntegerField(blank=True)),
                ('price', models.IntegerField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='ServerHardwareComponents',
            fields=[
                ('brand', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('product_type', models.CharField(max_length=32)),
                ('release_date', models.IntegerField(blank=True)),
                ('price', models.IntegerField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
