# Generated by Django 4.2.7 on 2024-04-16 18:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=32)),
                ('product_model', models.CharField(max_length=32)),
                ('product_type', models.CharField(max_length=32)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products')),
            ],
            options={
                'verbose_name': 'Product',
            },
        ),
        migrations.CreateModel(
            name='GlobalSearch',
            fields=[
                ('name', models.TextField()),
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='products.products')),
            ],
        ),
        migrations.CreateModel(
            name='HardwareComponent',
            fields=[
                ('products_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.products')),
                ('created', models.DateField(default=datetime.date.today)),
            ],
            bases=('products.products',),
        ),
        migrations.CreateModel(
            name='IoTDevice',
            fields=[
                ('products_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.products')),
                ('created', models.DateField(default=datetime.date.today)),
            ],
            options={
                'verbose_name': 'IoT device',
            },
            bases=('products.products',),
        ),
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('products_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.products')),
                ('created', models.DateField(default=datetime.date.today)),
            ],
            bases=('products.products',),
        ),
    ]
